### ISSUE TITLE
Change to American/British-style crossword

### ISSUE THREAD

**Issue by heatherleaf** [heatherleaf/crossword-maker#20]
Change the layout to be like an American/British crossword:
- No clues within the crosswords
- Solid black cells where there are no letters
- Clues are numbered (across/down)
- List of clues beneath the crossword
- Add side-words as clues too (i.e., words that are automatically added by the engine)

**Comment by ingemaradahl** [comment]
Could it be possible make this configurable/"toggleable"? Probably not, but it'd be a shame if it wouldn't be possible to create crosswords in the "nordic" style.

**Comment by heatherleaf** [comment]
Yes, I agree with you - I like the nordic style better. But it's more complicated (clues must fit in squares, squares can be split or merged, and we need a lot of arrows), so I will start with this American style first. Then try to have a "nordic" option

**Comment by heatherleaf** [comment]
Fixed in be412985613103c20cedf339f34823bc8f3119b8
